#!/bin/bash

	echo "Assignment #2-3, Brian Chenoweth, masc1367"

	if [ `grep -l 'Assignment #1' $1` ]
	then
	echo $1 "Assignment #1"
	fi
	
	if [ `grep -l 'Assignment #1' $2` ] 
	then
	echo $2 "Assignment #1" 
	fi 

	if [ `grep -l 'Assignment #1' $3` ] 
	then
	echo $3 "Assignment #1" 
	fi 
	
	if [ `grep -l 'Assignment #1' $4` ] 
	then
	echo $4 "Assignment #1" 
	fi 
	
	
	
	
	if [ `grep -l 'Assignment #2' $1` ] 
	then
	echo $1 "Assignment #2" 
	fi 

	if [ `grep -l 'Assignment #2' $2` ] 
	then
	echo $2 "Assignment #2" 
	fi 

	if [ `grep -l 'Assignment #2' $3` ] 
	then
	echo $3 "Assignment #2" 
	fi 
	
	
	if [ `grep -l 'Assignment #2' $4` ] 
	then
	echo $4 "Assignment #2" 
	fi 
	
	
	
	
	if [ `grep -l 'Assignment #3' $1` ] 
	then
	echo $1 "Assignment #3" 
	fi 

	if [ `grep -l 'Assignment #3' $2` ] 
	then
	echo $2 "Assignment #3" 
	fi 

	if [ `grep -l 'Assignment #3' $3` ] 
	then
	echo $3 "Assignment #3" 
	fi 
	
	if [ `grep -l 'Assignment #3' $4` ] 
	then
	echo $4 "Assignment #3" 
	fi 
	
	
	
	
	if [ `grep -l 'final' $1` ] 
	then
	echo $1 "Assignment #4" 
	fi 

	if [ `grep -l 'final' $2` ] 
	then
	echo $2 "Assignment #4" 
	fi 

	if [ `grep -l 'final' $3` ] 
	then
	echo $3 "Assignment #4" 
	fi 
	
	if [ `grep -l 'final' $4` ] 
	then
	echo $4 "Assignment #4" 
	fi 
